name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      tag:
      context:
    steps:
      - uses: kanga333/variable-mapper@master
        id: export
        with:
          key: "${{ inputs.environment }}"
          map: |
            {
              "testing": {
                "tag": "testing",
                "context": "do-nyc1-testing"
              },
              "staging": {
                "tag": "staging",
                "context": "do-nyc3-staging"
              },
              "production": {
                "tag": "latest",
                "context": "do-nyc3-production"
              }
            }
          export_to: env
      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }} with tag: ${{env.tag}} and kubectl context: ${{env.context}}"
