name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      TARGET_ENVIRONMET: >
        ${{ fromJson('{
          "testing": {
            "tag": "testing",
            "context": "do-nyc1-testing"
          },
          "staging": {
            "tag": "staging",
            "context": "do-nyc3-staging"
          },
          "production": {
            "tag": "latest",
            "context": "do-nyc3-production"
        }')[inputs.environment]}}
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }} with tag ${{ env.TARGET_ENVIRONMET.tag }} and kubectl context ${{ env.TARGET_ENVIRONMET.context }}"
