name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deploy_tag:
        required: true
        type: string
      kubectl_context:
        required: true
        type: string

jobs:
  verify:
    uses: ./.github/workflows/checks.yml
  deploy:
    needs: verify
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{ inputs.environment }} with tag ${{ inputs.deploy_tag }} and kubectl context ${{ inputs.kubectl_context }}"
